import numpy as np
import matplotlib.pyplot as plt

# Time simulation
t = np.linspace(0, 5, 500)
dt = t[1] - t[0]

# Virtual Dynamics Parameters (You tune these to change the "feel")
M_d = 2.0   # Virtual Mass (kg)
B_d = 15.0  # Virtual Damping (Ns/m)
K_d = 50.0  # Virtual Stiffness (N/m)

# Variables
x_ref = 0.0 # Target position
x_cmd = np.zeros_like(t) # Commanded position generated by admittance
v_cmd = np.zeros_like(t) # Commanded velocity

# Simulate external force: Human pushes with 50N from t=1 to t=2
F_ext = np.zeros_like(t)
F_ext[(t >= 1.0) & (t <= 2.0)] = 50.0

# Admittance Control Loop
for i in range(1, len(t)):
    # Calculate error between current yielded position and target
    e = x_cmd[i-1] - x_ref
    v = v_cmd[i-1]
    
    # Admittance Equation: M*a + B*v + K*e = F_ext
    # Solve for desired acceleration 'a'
    a_cmd = (F_ext[i] - B_d * v - K_d * e) / M_d
    
    # Integrate to get commanded velocity and position
    v_cmd[i] = v_cmd[i-1] + a_cmd * dt
    x_cmd[i] = x_cmd[i-1] + v_cmd[i] * dt

plt.figure(figsize=(10, 5))
plt.plot(t, F_ext, 'r--', label='External Force (N) [Scaled down for plot]')
plt.plot(t, x_cmd * 100, 'b', linewidth=2, label='Robot Position (cm) [Yielding]')
plt.title('1D Admittance Control: Robot Yielding to Human Push')
plt.xlabel('Time [s]')
plt.ylabel('Magnitude')
plt.grid(True)
plt.legend()
plt.show()